[package]
name = "format-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fmtrs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
regex = "1.8.1"
